# Generated by Django 6.1.1 on 2026-09-20 10:18

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=apps.documents.models.upload_path)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "DOCX"),
                            ("PPTX", "PPTX"),
                            ("PPT", "PPT"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_files",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-uploaded_at"],
                        name="uploaded_fi_user_id_c20811_idx",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="uploaded_fi_process_1a7a1f_idx",
                    ),
                ],
            },
        ),
    ]
