# Generated by Django 6.1.1 on 2026-09-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[("resume", "Resume"), ("ppt", "Presentation")],
                        default="resume",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0, help_text="Overall ATS compatibility score (0-100)"
                    ),
                ),
                (
                    "text_score",
                    models.FloatField(
                        default=0, help_text="Text extraction quality score"
                    ),
                ),
                (
                    "structure_score",
                    models.FloatField(default=0, help_text="Section structure score"),
                ),
                (
                    "formatting_score",
                    models.FloatField(default=0, help_text="Formatting quality score"),
                ),
                (
                    "keyword_score",
                    models.FloatField(default=0, help_text="Keyword coverage score"),
                ),
                (
                    "contact_score",
                    models.FloatField(default=0, help_text="Contact information score"),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, help_text="Full extracted text"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated analysis summary"
                    ),
                ),
                ("page_count", models.IntegerField(default=0)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "processing_time",
                    models.FloatField(
                        default=0, help_text="Processing time in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="documents.uploadedfile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analyses",
                "db_table": "analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("detected", models.BooleanField(default=True)),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0, help_text="Confidence of detection (0-1)"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "extracted_sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("important", "Important"),
                            ("suggestion", "Suggestion"),
                            ("good", "Good"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("text_extraction", "Text Extraction"),
                            ("section_structure", "Section Structure"),
                            ("formatting", "Formatting"),
                            ("keywords", "Keywords"),
                            ("contact_info", "Contact Information"),
                            ("content", "Content"),
                            ("layout", "Layout"),
                            ("images", "Images"),
                            ("slide_analysis", "Slide Analysis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "findings",
                "ordering": ["severity", "category"],
            },
        ),
        migrations.CreateModel(
            name="KeywordGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("keywords", models.JSONField(default=list)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_groups",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "keyword_groups",
            },
        ),
        migrations.CreateModel(
            name="SlideAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_number", models.IntegerField()),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "text_quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("warning", "Warning"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("has_images", models.BooleanField(default=False)),
                ("has_tables", models.BooleanField(default=False)),
                ("font_issues", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "slide_analyses",
                "ordering": ["slide_number"],
            },
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["uploaded_file", "-created_at"],
                name="analyses_uploade_cbaa29_idx",
            ),
        ),
    ]
